### ISSUE TITLE
GitHub Pages do not support Mermaid diagrams by default

### ISSUE THREAD

**Issue by dplanella** [linuxfoundation/devex-and-commsuccess#13]
While markdown files' content displayed on github.com renders Mermaid diagrams, GitHub Pages do not.

The reason is because GitHub pages is internally implemented with a specific Jekyll version and a [limited set of plugins](https://pages.github.com/versions/). No other jekyll plugins can be added (i.e. jekyll-mermaid) while using the built-in GitHub Pages functionality.

Compare:
- https://github.com/linuxfoundation/devex-and-commsuccess-handbook/tree/main/how-to-edit-the-handbook
- https://linuxfoundation.github.io/devex-and-commsuccess-handbook/how-to-edit-the-handbook

Note: these URLs might change as the content and structure of the handbook evolves.

It might be worth investigating this: https://jekyllrb.com/docs/continuous-integration/github-actions. That might allow using a standalone version of jekyll (or any other static site generator) outside of GitHub pages, build the static content including any 3rd party plugins, and then deploy it to the GitHub Pages environment to host the static content.

**Comment by jmertic** [comment]
Both of those links are 404 for me :-(

**Comment by dplanella** [comment]
@jmertic good catch, please try now.
