### ISSUE TITLE
Subpages content is not built

### ISSUE THREAD

**Issue by dplanella** [linuxfoundation/devex-and-commsuccess#19]
E.g. content from [subfolders](https://github.com/linuxfoundation/devex-and-commsuccess-handbook/tree/main/howto-edit) does not seem to be built and is thus not deployed on the final site.

**Comment by dplanella** [comment]
This seems to be related to GitHub pages not working as expected with frontmatter. I did not find a reference stating this explicitly, but adding frontmatter to a readme file has already brought some unexpected behavior. E.g. if frontmatter is added, and unless `permalink: index.html` is added, the HTML file is not rendered.

So the best course of action to keep things simple for now might be to remove the frontmatter altogether, and where configuration settings are needed, they'll be stated globally on the `_config.yml` file.

**Comment by jmertic** [comment]
That makes sense - much of what you were using for frontmatter ( i.e. titles ) can be done with an H1 in the doc itself.
