### ISSUE TITLE
Better define the difference between PR and MR (transition) in how-to-edit-the-handbook

### ISSUE THREAD

**Issue by krtaylor** [linuxfoundation/devex-and-commsuccess#59]
In the file how-to-edit-the-handbook/README.md, in the section Submit Pull Request (PR):

The section moves from PR to MR with no explanation on the new term (MR) or the transition, which may be confusing to those getting started with git/GitHub.

**Comment by dplanella** [comment]
Thanks @krtaylor, good catch. I introduced that mistake due to muscle memory. All instances should refer to PR. I submitted #60 with the fixes, for which your review would be appreciated.
