### ISSUE TITLE
Provide CY22Q3 project updates for SODA, TARS Fund

### ISSUE THREAD

**Issue by jmertic** [linuxfoundation/devex-and-commsuccess#63]
See https://github.com/linuxfoundation/devex-and-commsuccess/issues/48 for details

**Comment by jmertic** [comment]
Adding @yarille for this.

**Comment by dplanella** [comment]
@jmertic in the meantime, while @yarille is being added to the linuxfoundation org in GitHub, could you please coordinate getting the updates on the slide deck and updating the status here on the issue? Thanks!

**Comment by jmertic** [comment]
Confirmed with @yarille that both slides are done - closing.
