### ISSUE TITLE
Provide CY22Q4 project updates for CDF

### ISSUE THREAD

**Issue by dplanella** [linuxfoundation/devex-and-commsuccess#93]
See #88 for details

**Comment by micmarti85** [comment]
@dplanella reassigned to John

**Comment by dplanella** [comment]
@micmarti85 thanks for looking at this. I originally made this issue for both ASWF and CDF, in case you needed or wanted to provide an update for ASWF (even if no longer assigned to it). John has his own issue for ASWF and his other projects.

I've now removed the ASWF mention on the issue title and made it only about CDF. I'm thus reassigning back to you. Let me know if this makes sense.

**Comment by micmarti85** [comment]
CDF is good to go!
