### ISSUE TITLE
Provide CY22Q4 project updates for CCC, Nephio, SONiC, OpenBMC

### ISSUE THREAD

**Issue by dplanella** [linuxfoundation/devex-and-commsuccess#94]
See #88 for details

**Comment by dplanella** [comment]
Adding Lucy for SONiC only

**Comment by lucyhyde** [comment]
SONiC slide approved and uploaded to CY22Q4 deck.
Will close issue upon CCC/Nephio/OpenBMC completion!

**Comment by dplanella** [comment]
Excellent, thanks for the update!

**Comment by krtaylor** [comment]
CCC/Nephio/OpenBMC done!

**Comment by dplanella** [comment]
Thanks @krtaylor and @lucyhyde!
