### ISSUE TITLE
Provide CY22Q3 project updates for LF AI & Data, PyTorch

### ISSUE THREAD

**Issue by dplanella** [linuxfoundation/devex-and-commsuccess#96]
See #88 for details. There is no slide for PyTorch, which we might want to add if Ibrahim thinks it makes sense.

**Comment by jzcardoso** [comment]
There is a slide for PyTorch which was already added.

Updates for LF AI & Data and PyTorch are done.

**Comment by dplanella** [comment]
Excellent, thanks!
